# 660710174 บุณยานุช ศรีจันทร์ฉาย

# pandas ใช้งานสำหรับการจัดการข้อมูลแบบตาราง ตั้งชื่อว่า pd
# numpy ใช้สำหรับคำนวณวิทยาศาสตร์และคณิตศาสตร์, การจัดการ array, matrix, และฟังก์ชันเชิงตัวเลขทั่วไป ตั้งชื่อว่า np
# datetime ใช้เพื่อสร้างและจัดการวันและเวลา timedelta ใช้สร้างช่วงระยะเวลาสำหรับการบวกลบวัน เวลา
# warnings ใช้สำหรับจัดการข้อความ "คำเตือน" ที่อาจเกิดขึ้นขณะรันโปรแกรม
# ignore เมื่อโปรแกรมรัน ถ้าเกิด warning จะไม่แสดงข้อความเตือนเหล่านั้น

In [51]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# อ่านไฟล์ที่ชื่อว่า student.csv เพื่อที่จะได้นำข้อมูลในไฟล์มาใช้งาน โดยตั้งชื่อในการเรียกใช้งานไฟล์ คือ df

In [52]:
df = pd.read_csv("student.csv")

# แสดงข้อมูลของ df

In [53]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

# บอกขนาดตารางข้อมูลของdf 20 คือ จำนวนแถว, 10 จำนวนคอลัมน์

In [54]:
df.shape

(20, 10)

# แสดงข้อมูลdf 5 บรรทัดแรก

In [55]:
df.head()

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27

# ดูข้อมูลของdfว่าเป็นค่าว่าง(ไม่ได้ใส่ข้อมูลลงในdataframe)ไหม ถ้าเป็น False คือ ไม่ว่าง ถ้าเป็น True คือว่าง

In [56]:
df.isnull()

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,True,True,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,True,True,True,False,True,False,True,False
11,False,False,False,False,False,True,False,True,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,True,False,False,False,False,False
18,False,False,True,False,False,True,False,False,True,False
19,False,False,False,True,False,False,False,False,False,False

# แสดงผลรวมของค่าว่าง(ที่มีค่าเป็นTrueในตาราง)ในแต่ละคอลัมน์

In [57]:
df.isnull().sum()

รหัสนักศึกษา               0
ชื่อ                       1
อายุ                       3
เพศ                        2
คณะ                        2
GPA                        2
ส่วนสูง_cm                 1
น้ำหนัก_kg                 2
ชั่วโมงเรียน_ต่อสัปดาห์    2
วันที่ลงทะเบียน            0
dtype: int64

# แสดงผลรวมของค่าว่าง(True)ทั้งหมดในตาราง

In [58]:
df.isnull().sum().sum()

np.int64(15)

# แสดงจำนวนของคณะที่ไม่ซ้ำกันทั้งหมดในdataframe

In [59]:
df['คณะ'].nunique()

14

# copyไฟล์ต้นฉบับเอาไว้เพื่อเอาไว้เรียกดูข้อมูลที่ยังไม่ได้เอาไปทำอะไร

In [60]:
df_original = df.copy()

In [61]:
df_original

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

# สรุปข้อมูลในdf จำนวนแถวและคอลัมน์ คอลัมน์ทั้งหมดในdf จำนวนnon-nullในแต่ละคอลัมน์ ชนิดข้อมูลแต่ละคอลัมน์ และใช้หน่วยความจำเท่าไหร่

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   รหัสนักศึกษา             20 non-null     int64
 1   ชื่อ                     19 non-null     object
 2   อายุ                     17 non-null     float64
 3   เพศ                      18 non-null     object
 4   คณะ                      18 non-null     object
 5   GPA                      18 non-null     float64
 6   ส่วนสูง_cm               19 non-null     float64
 7   น้ำหนัก_kg               18 non-null     float64
 8   ชั่วโมงเรียน_ต่อสัปดาห์  18 non-null     float64
 9   วันที่ลงทะเบียน          20 non-null     object
dtypes: float64(5), int64(1), object(4)
memory usage: 1.7+ KB

# คำนวนและแสดงข้อมูลสถิติพื้นฐาน

In [63]:
df.describe()

,รหัสนักศึกษา,อายุ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์
count,20.00000,17.000000,18.000000,19.000000,18.000000,18.000000
mean,64010.50000,28.470588,3.246111,167.684211,63.611111,21.388889
std,5.91608,31.337114,1.123326,5.706260,10.279270,6.598920
min,64001.00000,19.000000,-1.000000,158.000000,48.000000,10.000000
25%,64005.75000,20.000000,3.215000,163.500000,55.250000,16.500000
50%,64010.50000,21.000000,3.450000,168.000000,63.000000,21.500000
75%,64015.25000,22.000000,3.670000,171.500000,71.500000,25.750000
max,64020.00000,150.000000,4.500000,180.000000,82.000000,35.000000

# แสดงข้อมูลdf โดยที่ต้องไม่มีค่าว่างอยู่ใน dataframe

In [64]:
df_clean = df.dropna()

In [65]:
df_clean

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24

# แสดงค่าเฉลี่ยของส่วนสูงใน df

In [66]:
mean_height = df['ส่วนสูง_cm'].mean()

In [67]:
mean_height

np.float64(167.68421052631578)

In [68]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

# หาค่าเฉลี่ยของอายุและนำค่าเฉลี่ยที่ได้ไปใส่แทนที่อายุที่เป็นค่าว่าง(NaN)

In [69]:
mean_age = df['อายุ'].mean()
mean_age

np.float64(28.470588235294116)

In [70]:
df['อายุ'].fillna(mean_age, inplace=True)

In [71]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,28.470588,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.000000,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

# แทนที่ค่าว่าง(NaN)ในคอลัมน์คณะด้วยฐานนิยมของคอลัมน์คณะ(เจอคณะใดคณะหนึ่งเยอะที่สุดในคอลัมน์)ซึ่งฐานนิยมคือ Science ก็จะนำ Science ไปแทนที่ค่าว่างในคอลัมน์คณะ

In [72]:
df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)

In [73]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,28.470588,NaN,Science,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.000000,หญิง,Science,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

# แสดงคอลัมน์คณะโดยที่ทำให้คณะเดียวกันที่เขียนไม่เหมือนกันให้เขียนเหมือนกัน

In [74]:
def standardize_faculty(name):
    if name in ['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์','Sci']:
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'Arts', 'Liberal Arts']:
        return 'ศิลปศาสตร์'
    elif name in ['วิศวะ','วิศวกรรม','Engineering','วิศวฯ','วิศวกรรมศาสตร์']:
        return 'วิศวกรรมศาสตร์'
    else:
        return name

In [75]:
df['คณะ_มาตรฐาน'] = df['คณะ'].apply(standardize_faculty)

In [76]:
df['คณะ_มาตรฐาน']

0        วิทยาศาสตร์
1        วิทยาศาสตร์
2        วิทยาศาสตร์
3        วิทยาศาสตร์
4     วิศวกรรมศาสตร์
5     วิศวกรรมศาสตร์
6     วิศวกรรมศาสตร์
7         ศิลปศาสตร์
8         ศิลปศาสตร์
9         ศิลปศาสตร์
10       วิทยาศาสตร์
11       วิทยาศาสตร์
12    วิศวกรรมศาสตร์
13        ศิลปศาสตร์
14       วิทยาศาสตร์
15       วิทยาศาสตร์
16    วิศวกรรมศาสตร์
17       วิทยาศาสตร์
18        ศิลปศาสตร์
19       วิทยาศาสตร์
Name: คณะ_มาตรฐาน, dtype: object

# แสดงข้อมูลที่อยู่ในควอไทล์แรกกับควอไทล์ที่สาม

In [77]:
Q1 = df['อายุ'].quantile(0.25)
Q3 = df['อายุ'].quantile(0.75)

In [78]:
Q1, Q3

(np.float64(20.0), np.float64(22.25))

# แสดงข้อมูลที่เป็นส่วนต่างระหว่างควอไทล์แรกกับควอไทล์ที่สาม

In [79]:
IQR = Q3 - Q1

In [80]:
IQR

np.float64(2.25)

# แสดงขอบเขตล่างกับขอบเขตบน สำหรับวิเคราะห์หาค่าผิดปกติ

In [81]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [82]:
lower_bound, upper_bound

(np.float64(16.625), np.float64(25.625))

# แสดงข้อมูลอายุที่ไม่ต่ำกว่าขอบเขตล่างและไม่สูงกว่าขอบเขตบน

In [83]:
df_no_outliers = df[(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound)]

In [84]:
df_no_outliers

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,วิทยาศาสตร์
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05,วิทยาศาสตร์
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,วิทยาศาสตร์
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27,วิศวกรรมศาสตร์
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05,วิศวกรรมศาสตร์
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,ศิลปศาสตร์
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11,ศิลปศาสตร์
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03,ศิลปศาสตร์
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26,วิทยาศาสตร์
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26,วิศวกรรมศาสตร์
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08,ศิลปศาสตร์
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06,วิทยาศาสตร์
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,วิทยาศาสตร์
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,วิศวกรรมศาสตร์
17,64018,ยุพา,21.0,หญิง,Science,3.23,161.0,50.0,27.0,2024-01-08,วิทยาศาสตร์
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06,วิทยาศาสตร์

# แสดงข้อมูลอายุโดยถ้าเป็นTrue คือ ค่าอายุมากกว่าหรือเท่ากับขอบเขตล่าง แต่ถ้าเป็นFalse คือ ค่าอายุน้อยกว่าขอบเขตล่าง

In [85]:
df['อายุ'] >= lower_bound

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
Name: อายุ, dtype: bool

# แสดงข้อมูลอายุโดยถ้าเป็นTrue คือ ค่าอายุน้อยกว่าหรือเท่ากับขอบเขตบน แต่ถ้าเป็นFalse คือ ค่าอายุมากกว่ากว่าขอบเขตบน

In [86]:
df['อายุ'] <= upper_bound

0      True
1      True
2     False
3      True
4      True
5     False
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19     True
Name: อายุ, dtype: bool

# แสดงข้อมูลอายุโดยที่ถ้าเป็น True คือ ค่าอายุมากกว่าหรือเท่ากับขอบเขตล่างและน้อยกว่าหรือเท่ากับขอบเขตบน แต่ถ้าเป็น False คือ ค่าอายุจะน้อยกว่าขอบเขตล่างและมากกว่าขอบเขตบน

In [87]:
(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound)

0      True
1      True
2     False
3      True
4      True
5     False
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19     True
Name: อายุ, dtype: bool

# แปลงคอลัมน์คณะเป็นรูปแบบ One-Hot Encoding มีการสร้างคอลัมน์ใหม่ของแต่ละคณะ และแต่ละแถวจะมีค่า 1 ในคอลัมน์ที่ตรงกับคณะของตน และ 0 ในคอลัมน์อื่นๆ

In [88]:
data_encoded = pd.get_dummies(df, columns=['คณะ'])
print(data_encoded*1)

    รหัสนักศึกษา      ชื่อ        อายุ     เพศ   GPA  ส่วนสูง_cm  น้ำหนัก_kg  \
0          64001     สมชาย   20.000000     ชาย  3.21       170.0        65.0
1          64002    สมหญิง   21.000000    หญิง  3.45       165.0        58.0
2          64003       NaN   28.470588    Male  3.67       175.0         NaN
3          64004  สมศักดิ์   22.000000       ช -1.00       168.0        70.0
4          64005      สมใจ   19.000000       ญ  3.89       160.0        52.0
5          64006     กานต์  150.000000     ชาย  3.12       172.0        75.0
6          64007     กิตติ   21.000000    หญิง  4.50       158.0        48.0
7          64008      จิรา   20.000000       F  2.98       180.0        82.0
8          64009    ชนาธิป   23.000000       M  3.34       163.0        55.0
9          64010      ดารา   21.000000    หญิง  3.56       167.0        60.0
10         64011      ธีระ   28.470588     NaN  3.78         NaN        68.0
11         64012       นภา   22.000000     ชาย   NaN       171.0         NaN
12         64013     บุญมี   20.000000    หญิง  3.23       169.0        72.0
13         64014     ปรีชา   21.000000     ชาย  3.45       164.0        54.0
14         64015     พิมพ์   22.000000  Female  3.67       162.0        56.0
15         64016      ภูมิ   19.000000       ช  3.89       173.0        78.0
16         64017      มานี   20.000000       ญ  3.01       166.0        62.0
17         64018      ยุพา   21.000000    หญิง  3.23       161.0        50.0
18         64019     รัตนา   28.470588     ชาย   NaN       174.0        76.0
19         64020     ลัดดา   22.000000     NaN  3.45       168.0        64.0

    ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน     คณะ_มาตรฐาน  ...  คณะ_Science  \
0                      15.0      2024-01-23     วิทยาศาสตร์  ...            0
1                      20.0      2024-02-05     วิทยาศาสตร์  ...            0
2                      25.0      2024-01-13     วิทยาศาสตร์  ...            1
3                      10.0      2023-12-30     วิทยาศาสตร์  ...            0
4                      30.0      2024-01-27  วิศวกรรมศาสตร์  ...            0
5                      12.0      2023-12-23  วิศวกรรมศาสตร์  ...            0
6                      35.0      2024-01-05  วิศวกรรมศาสตร์  ...            0
7                      18.0      2024-01-23      ศิลปศาสตร์  ...            0
8                      22.0      2024-02-11      ศิลปศาสตร์  ...            0
9                      28.0      2024-01-03      ศิลปศาสตร์  ...            0
10                      NaN      2024-01-07     วิทยาศาสตร์  ...            1
11                     16.0      2023-12-26     วิทยาศาสตร์  ...            0
12                     24.0      2023-12-26  วิศวกรรมศาสตร์  ...            0
13                     19.0      2024-01-08      ศิลปศาสตร์  ...            0
14                     26.0      2024-02-06     วิทยาศาสตร์  ...            0
15                     14.0      2024-01-20     วิทยาศาสตร์  ...            0
16                     21.0      2024-01-24  วิศวกรรมศาสตร์  ...            0
17                     27.0      2024-01-08     วิทยาศาสตร์  ...            1
18                      NaN      2023-12-18      ศิลปศาสตร์  ...            0
19                     23.0      2024-01-06     วิทยาศาสตร์  ...            1

    คณะ_คณะวิทยาศาสตร์  คณะ_วิทยาศาสตร์  คณะ_วิทย์  คณะ_วิศวกรรม  \
0                    0                1          0             0
1                    0                0          1             0
2                    0                0          0             0
3                    1                0          0             0
4                    0                0          0             0
5                    0                0          0             0
6                    0                0          0             1
7                    0                0          0             0
8                    0                0          0             0
9                    0                0          0             0
10                   0                0          0             0
11                   0                0          1             0
12                   0                0          0             0
13                   0                0          0             0
14                   0                0          0             0
15                   0                1          0             0
16                   0                0          0             0
17                   0                0          0             0
18                   0                0          0             0
19                   0                0          0             0

    คณะ_วิศวกรรมศาสตร์  คณะ_วิศวฯ  คณะ_วิศวะ  คณะ_ศิลปศาสตร์  คณะ_ศิลป์
0                    0          0          0               0          0
1                    0          0          0               0          0
2                    0          0          0               0          0
3                    0          0          0               0          0
4                    0          0          1               0          0
5                    0          0          0               0          0
6                    0          0          0               0          0
7                    0          0          0               1          0
8                    0          0          0               0          0
9                    0          0          0               0          1
10                   0          0          0               0          0
11                   0          0          0               0          0
12                   0          1          0               0          0
13                   0          0          0               0          0
14                   0          0          0               0          0
15                   0          0          0               0          0
16                   1          0          0               0          0
17                   0          0          0               0          0
18                   0          0          0               1          0
19                   0          0          0               0          0

[20 rows x 24 columns]

#ทำการแปลงข้อมูลในคอลัมน์'วันที่ลงทะเบียน'ให้กลายเป็นชนิดข้อมูลdatetimeของpandasก่อน เพื่อที่จะสามารถใช้functionวัน-เวลาของpandasได้

In [89]:
df['วันที่ลงทะเบียน'] = pd.to_datetime(df['วันที่ลงทะเบียน'])

# สร้างคอลัมน์ใหม่ชื่อว่า'วันในสัปดาห์'และใส่ข้อมูลลงในคอลัมน์โดยข้อมูลเอามาจากคอลัมน์'วันที่ลงทะเบียน'ดูจากวันที่และนำมาแปลงเป็นวันเป็นภาษาอังกฤษ

In [90]:
df['วันในสัปดาห์'] = df['วันที่ลงทะเบียน'].dt.day_name()

In [91]:
df['วันในสัปดาห์']

0       Tuesday
1        Monday
2      Saturday
3      Saturday
4      Saturday
5      Saturday
6        Friday
7       Tuesday
8        Sunday
9     Wednesday
10       Sunday
11      Tuesday
12      Tuesday
13       Monday
14      Tuesday
15     Saturday
16    Wednesday
17       Monday
18       Monday
19     Saturday
Name: วันในสัปดาห์, dtype: object

In [92]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน,วันในสัปดาห์
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,วิทยาศาสตร์,Tuesday
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05,วิทยาศาสตร์,Monday
2,64003,NaN,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-13,วิทยาศาสตร์,Saturday
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,วิทยาศาสตร์,Saturday
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27,วิศวกรรมศาสตร์,Saturday
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23,วิศวกรรมศาสตร์,Saturday
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05,วิศวกรรมศาสตร์,Friday
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,ศิลปศาสตร์,Tuesday
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-02-11,ศิลปศาสตร์,Sunday
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03,ศิลปศาสตร์,Wednesday
10,64011,ธีระ,28.470588,NaN,Science,3.78,NaN,68.0,NaN,2024-01-07,วิทยาศาสตร์,Sunday
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26,วิทยาศาสตร์,Tuesday
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26,วิศวกรรมศาสตร์,Tuesday
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08,ศิลปศาสตร์,Monday
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06,วิทยาศาสตร์,Tuesday
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,วิทยาศาสตร์,Saturday
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,วิศวกรรมศาสตร์,Wednesday
17,64018,ยุพา,21.000000,หญิง,Science,3.23,161.0,50.0,27.0,2024-01-08,วิทยาศาสตร์,Monday
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18,ศิลปศาสตร์,Monday
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06,วิทยาศาสตร์,Saturday

#สร้างคอลัมน์ใหม่ชื่อ'จำนวนคาบ'ข้อมูลที่นำมาใส่ในคอลัมน์มาจากการหาชั่วโมงเรียนต่อสัปดาห์ โดยจะทำข้อมูลให้เป็นช่วงๆ เช่น ชั่วโมงเรียนต่อสัปดาห์ คือ 15 อยู่ในช่วงที่กำหนดไว้คือ 8-16 ดังนั้นก็จะได้จำนวนคาบคือ 2 วัน ก็จะนำ 2 วัน ได้ไปใส่ลงในคอลัมน์'จำนวนคาบ'

In [93]:
df['จำนวนคาบ'] = pd.cut(df['ชั่วโมงเรียน_ต่อสัปดาห์'],
                                  bins=[0, 8, 16, 24, 32, 40],
                                  labels=['1 วัน', '2 วัน', '3 วัน', '4 วัน', '5 วัน'])

In [94]:
df['จำนวนคาบ']

0     2 วัน
1     3 วัน
2     4 วัน
3     2 วัน
4     4 วัน
5     2 วัน
6     5 วัน
7     3 วัน
8     3 วัน
9     4 วัน
10      NaN
11    2 วัน
12    3 วัน
13    3 วัน
14    4 วัน
15    2 วัน
16    3 วัน
17    4 วัน
18      NaN
19    3 วัน
Name: จำนวนคาบ, dtype: category
Categories (5, object): ['1 วัน' < '2 วัน' < '3 วัน' < '4 วัน' < '5 วัน']

In [95]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน,วันในสัปดาห์,จำนวนคาบ
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,วิทยาศาสตร์,Tuesday,2 วัน
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05,วิทยาศาสตร์,Monday,3 วัน
2,64003,NaN,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-13,วิทยาศาสตร์,Saturday,4 วัน
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,วิทยาศาสตร์,Saturday,2 วัน
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27,วิศวกรรมศาสตร์,Saturday,4 วัน
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23,วิศวกรรมศาสตร์,Saturday,2 วัน
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05,วิศวกรรมศาสตร์,Friday,5 วัน
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,ศิลปศาสตร์,Tuesday,3 วัน
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-02-11,ศิลปศาสตร์,Sunday,3 วัน
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03,ศิลปศาสตร์,Wednesday,4 วัน
10,64011,ธีระ,28.470588,NaN,Science,3.78,NaN,68.0,NaN,2024-01-07,วิทยาศาสตร์,Sunday,NaN
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26,วิทยาศาสตร์,Tuesday,2 วัน
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26,วิศวกรรมศาสตร์,Tuesday,3 วัน
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08,ศิลปศาสตร์,Monday,3 วัน
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06,วิทยาศาสตร์,Tuesday,4 วัน
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,วิทยาศาสตร์,Saturday,2 วัน
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,วิศวกรรมศาสตร์,Wednesday,3 วัน
17,64018,ยุพา,21.000000,หญิง,Science,3.23,161.0,50.0,27.0,2024-01-08,วิทยาศาสตร์,Monday,4 วัน
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18,ศิลปศาสตร์,Monday,NaN
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06,วิทยาศาสตร์,Saturday,3 วัน

#สร้างคอลัมน์BMI ข้อมูลมาจากการคำนวนหาค่าจากน้ำหนักและส่วนสูง

In [96]:
df['BMI'] = df['น้ำหนัก_kg'] / (df['ส่วนสูง_cm']/100)**2

In [97]:
df['BMI']

0     22.491349
1     21.303949
2           NaN
3     24.801587
4     20.312500
5     25.351541
6     19.227688
7     25.308642
8     20.700817
9     21.513859
10          NaN
11          NaN
12    25.209201
13    20.077335
14    21.338211
15    26.061679
16    22.499637
17    19.289379
18    25.102391
19    22.675737
Name: BMI, dtype: float64

In [98]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน,วันในสัปดาห์,จำนวนคาบ,BMI
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,วิทยาศาสตร์,Tuesday,2 วัน,22.491349
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05,วิทยาศาสตร์,Monday,3 วัน,21.303949
2,64003,NaN,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-13,วิทยาศาสตร์,Saturday,4 วัน,NaN
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,วิทยาศาสตร์,Saturday,2 วัน,24.801587
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27,วิศวกรรมศาสตร์,Saturday,4 วัน,20.312500
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23,วิศวกรรมศาสตร์,Saturday,2 วัน,25.351541
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05,วิศวกรรมศาสตร์,Friday,5 วัน,19.227688
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,ศิลปศาสตร์,Tuesday,3 วัน,25.308642
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-02-11,ศิลปศาสตร์,Sunday,3 วัน,20.700817
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03,ศิลปศาสตร์,Wednesday,4 วัน,21.513859
10,64011,ธีระ,28.470588,NaN,Science,3.78,NaN,68.0,NaN,2024-01-07,วิทยาศาสตร์,Sunday,NaN,NaN
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26,วิทยาศาสตร์,Tuesday,2 วัน,NaN
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26,วิศวกรรมศาสตร์,Tuesday,3 วัน,25.209201
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08,ศิลปศาสตร์,Monday,3 วัน,20.077335
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06,วิทยาศาสตร์,Tuesday,4 วัน,21.338211
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,วิทยาศาสตร์,Saturday,2 วัน,26.061679
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,วิศวกรรมศาสตร์,Wednesday,3 วัน,22.499637
17,64018,ยุพา,21.000000,หญิง,Science,3.23,161.0,50.0,27.0,2024-01-08,วิทยาศาสตร์,Monday,4 วัน,19.289379
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18,ศิลปศาสตร์,Monday,NaN,25.102391
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06,วิทยาศาสตร์,Saturday,3 วัน,22.675737